### ISSUE TITLE
Missing xcursorgen

### ISSUE THREAD

**Issue by e-minguez** [auteiy/cursorsPosy#1]
While running the create.sh scripts it doesn't generate the cursors because a missing dependency:
```
Progress : [##########------------------------------] 25%buildFunctions.sh: line 41: xcursorgen: command not found
buildFunctions.sh: line 41: xcursorgen: command not found
...
buildFunctions.sh: line 230: xcursorgen: command not found
```

It would be nice to:

- Check if xcursorgen is installed
- Add instructions on dependencies/prerrequisites
- Have a 'ready to use' zip containing the icons

Thanks!

**Comment by e-minguez** [comment]
In Fedora 30, xcursorgen can be installed with `dnf install xorg-x11-apps` just in case.

**Comment by eyenalxai** [comment]
- [x] Check if xcursorgen is installed
- [x] Add instructions on dependencies/prerrequisites
- [x] Have a 'ready to use' zip containing the icons

Thank you for your contribution!
