### ISSUE TITLE
Prebuilt link broken

### ISSUE THREAD

**Issue by jallbrit** [auteiy/cursorsPosy#2]
The `README` includes a link with pre-built cursors:

[https://git.auteiy.me/dmitry/cursorsPosy/-/archive/master/cursorsPosy-master.tar.gz?path=Prebuilt](https://git.auteiy.me/dmitry/cursorsPosy/-/archive/master/cursorsPosy-master.tar.gz?path=Prebuilt)

however, this link is broken and the "file" size that's downloaded is 0.

**Comment by eyenalxai** [comment]
It’s fixed!

**Comment by jallbrit** [comment]
Looks great, thanks!
