### ISSUE TITLE
Manual build instructions broken

### ISSUE THREAD

**Issue by jallbrit** [auteiy/cursorsPosy#3]
The README build instructions do not work.

> Run `bash Main/create.sh`

There is no `Main` directory when `git clone`'d.

I believe the correct instructions should be:

```bash
git clone https://github.com/auteiy/cursorsPosy (or whatever git repo you want to be cloned)
cd cursorsPosy/src
bash create.sh
...
cd ../themes
```

To install a particular theme:

```
cp -r <theme-name> ~/.icons/
```

To install all themes:

```
cp -r * ~/.icons
```

**Comment by eyenalxai** [comment]
Should be fixed too!
