### ISSUE TITLE
Progress cursor is wrongly positioned

### ISSUE THREAD

**Issue by gamehelp16** [auteiy/cursorsPosy#4]
Thank you for the cursor pack, it looks amazing! However it looks like there's a little problem on the cursor pack. The "progress" cursor (the one with the pointer and rainbow hourglass) is wrongly positioned and thus it may cause users to click at the wrong place when the cursor is in that state (I hope my explanation makes sense lol). I'm using the black tiny variant btw.

**Comment by eyenalxai** [comment]
Somewhat fixed. Will fix properly later.
